package pe.modelo.pojo.vista;
// Generated 29-ago-2017 18:25:42 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VwSelDocumentoVenta generated by hbm2java
 */
@Entity
@Table(name = "vw_aut_cliente",
        schema = "ventas"
)
public class VwAutCliente implements java.io.Serializable {

    private Long id;
    private String codigoTipoDocumentoEntidad;
    private String documento;
    private String nombre;

    public VwAutCliente() {
    }

    @Id
    @Column(name = "id", insertable = false, updatable = false)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "codigo_tipo_documento_entidad", insertable = false, updatable = false)
    public String getCodigoTipoDocumentoEntidad() {
        return codigoTipoDocumentoEntidad;
    }

    public void setCodigoTipoDocumentoEntidad(String codigoTipoDocumentoEntidad) {
        this.codigoTipoDocumentoEntidad = codigoTipoDocumentoEntidad;
    }

    @Column(name = "documento", insertable = false, updatable = false)
    public String getDocumento() {
        return documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

    @Column(name = "nombre", insertable = false, updatable = false)
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}
