package entity;
// Generated 11/08/2017 06:01:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblrolRol generated by hbm2java
 */
@Entity
@Table(name="tblrol_rol"
    ,schema="administracion"
    , uniqueConstraints = @UniqueConstraint(columnNames="rol_nombre") 
)
public class TblrolRol  implements java.io.Serializable {


     private long rolId;
     private TblusuarioUsu tblusuarioUsuByUsuIdcreacion;
     private TblusuarioUsu tblusuarioUsuByUsuIdmodificacion;
     private String rolNombre;
     private String rolDescripcion;
     private boolean rolAdmin;
     private Date rolFechacreacion;
     private Date rolFechamodificacion;
     private Set<TblusuarioUsu> tblusuarioUsus = new HashSet<TblusuarioUsu>(0);

    public TblrolRol() {
    }

	
    public TblrolRol(long rolId, TblusuarioUsu tblusuarioUsuByUsuIdcreacion, String rolNombre, String rolDescripcion, boolean rolAdmin, Date rolFechacreacion) {
        this.rolId = rolId;
        this.tblusuarioUsuByUsuIdcreacion = tblusuarioUsuByUsuIdcreacion;
        this.rolNombre = rolNombre;
        this.rolDescripcion = rolDescripcion;
        this.rolAdmin = rolAdmin;
        this.rolFechacreacion = rolFechacreacion;
    }
    public TblrolRol(long rolId, TblusuarioUsu tblusuarioUsuByUsuIdcreacion, TblusuarioUsu tblusuarioUsuByUsuIdmodificacion, String rolNombre, String rolDescripcion, boolean rolAdmin, Date rolFechacreacion, Date rolFechamodificacion, Set<TblusuarioUsu> tblusuarioUsus) {
       this.rolId = rolId;
       this.tblusuarioUsuByUsuIdcreacion = tblusuarioUsuByUsuIdcreacion;
       this.tblusuarioUsuByUsuIdmodificacion = tblusuarioUsuByUsuIdmodificacion;
       this.rolNombre = rolNombre;
       this.rolDescripcion = rolDescripcion;
       this.rolAdmin = rolAdmin;
       this.rolFechacreacion = rolFechacreacion;
       this.rolFechamodificacion = rolFechamodificacion;
       this.tblusuarioUsus = tblusuarioUsus;
    }
   
     @Id 

    
    @Column(name="rol_id", unique=true, nullable=false)
    public long getRolId() {
        return this.rolId;
    }
    
    public void setRolId(long rolId) {
        this.rolId = rolId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usu_idcreacion", nullable=false)
    public TblusuarioUsu getTblusuarioUsuByUsuIdcreacion() {
        return this.tblusuarioUsuByUsuIdcreacion;
    }
    
    public void setTblusuarioUsuByUsuIdcreacion(TblusuarioUsu tblusuarioUsuByUsuIdcreacion) {
        this.tblusuarioUsuByUsuIdcreacion = tblusuarioUsuByUsuIdcreacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usu_idmodificacion")
    public TblusuarioUsu getTblusuarioUsuByUsuIdmodificacion() {
        return this.tblusuarioUsuByUsuIdmodificacion;
    }
    
    public void setTblusuarioUsuByUsuIdmodificacion(TblusuarioUsu tblusuarioUsuByUsuIdmodificacion) {
        this.tblusuarioUsuByUsuIdmodificacion = tblusuarioUsuByUsuIdmodificacion;
    }

    
    @Column(name="rol_nombre", unique=true, nullable=false, length=50)
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }

    
    @Column(name="rol_descripcion", nullable=false)
    public String getRolDescripcion() {
        return this.rolDescripcion;
    }
    
    public void setRolDescripcion(String rolDescripcion) {
        this.rolDescripcion = rolDescripcion;
    }

    
    @Column(name="rol_admin", nullable=false)
    public boolean isRolAdmin() {
        return this.rolAdmin;
    }
    
    public void setRolAdmin(boolean rolAdmin) {
        this.rolAdmin = rolAdmin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rol_fechacreacion", nullable=false, length=29)
    public Date getRolFechacreacion() {
        return this.rolFechacreacion;
    }
    
    public void setRolFechacreacion(Date rolFechacreacion) {
        this.rolFechacreacion = rolFechacreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="rol_fechamodificacion", length=29)
    public Date getRolFechamodificacion() {
        return this.rolFechamodificacion;
    }
    
    public void setRolFechamodificacion(Date rolFechamodificacion) {
        this.rolFechamodificacion = rolFechamodificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblrolRol")
    public Set<TblusuarioUsu> getTblusuarioUsus() {
        return this.tblusuarioUsus;
    }
    
    public void setTblusuarioUsus(Set<TblusuarioUsu> tblusuarioUsus) {
        this.tblusuarioUsus = tblusuarioUsus;
    }




}


