package entity;
// Generated 11/08/2017 06:01:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblusuarioUsu generated by hbm2java
 */
@Entity
@Table(name = "tblusuario_usu", schema = "administracion", uniqueConstraints = @UniqueConstraint(columnNames = "usu_nombre")
)
public class TblusuarioUsu implements java.io.Serializable {

    private long usuId;
    private TblrolRol tblrolRol;
    private TblusuarioUsu tblusuarioUsuByUsuIdcreacion;
    private TblusuarioUsu tblusuarioUsuByUsuIdmodificacion;
    private String usuNombre;
    private String usuContrasenhia;
    private String usuNombrecompleto;
    private Date usuFechacreacion;
    private Date usuFechamodificacion;
    private long empId;
    private Set<TblrolRol> tblrolRolsForUsuIdcreacion = new HashSet<TblrolRol>(0);
    private Set<TblrolRol> tblrolRolsForUsuIdmodificacion = new HashSet<TblrolRol>(0);
    private Set<TblusuarioUsu> tblusuarioUsusForUsuIdcreacion = new HashSet<TblusuarioUsu>(0);
    private Set<TblusuarioUsu> tblusuarioUsusForUsuIdmodificacion = new HashSet<TblusuarioUsu>(0);

    public TblusuarioUsu() {
    }

    public TblusuarioUsu(long usuId, TblrolRol tblrolRol, TblusuarioUsu tblusuarioUsuByUsuIdcreacion, String usuContrasenhia, String usuNombrecompleto, Date usuFechacreacion, long empId) {
        this.usuId = usuId;
        this.tblrolRol = tblrolRol;
        this.tblusuarioUsuByUsuIdcreacion = tblusuarioUsuByUsuIdcreacion;
        this.usuContrasenhia = usuContrasenhia;
        this.usuNombrecompleto = usuNombrecompleto;
        this.usuFechacreacion = usuFechacreacion;
        this.empId = empId;
    }

    public TblusuarioUsu(long usuId, TblrolRol tblrolRol, TblusuarioUsu tblusuarioUsuByUsuIdcreacion, TblusuarioUsu tblusuarioUsuByUsuIdmodificacion, String usuNombre, String usuContrasenhia, String usuNombrecompleto, Date usuFechacreacion, Date usuFechamodificacion, long empId, Set<TblrolRol> tblrolRolsForUsuIdcreacion, Set<TblrolRol> tblrolRolsForUsuIdmodificacion, Set<TblusuarioUsu> tblusuarioUsusForUsuIdcreacion, Set<TblusuarioUsu> tblusuarioUsusForUsuIdmodificacion) {
        this.usuId = usuId;
        this.tblrolRol = tblrolRol;
        this.tblusuarioUsuByUsuIdcreacion = tblusuarioUsuByUsuIdcreacion;
        this.tblusuarioUsuByUsuIdmodificacion = tblusuarioUsuByUsuIdmodificacion;
        this.usuNombre = usuNombre;
        this.usuContrasenhia = usuContrasenhia;
        this.usuNombrecompleto = usuNombrecompleto;
        this.usuFechacreacion = usuFechacreacion;
        this.usuFechamodificacion = usuFechamodificacion;
        this.empId = empId;
        this.tblrolRolsForUsuIdcreacion = tblrolRolsForUsuIdcreacion;
        this.tblrolRolsForUsuIdmodificacion = tblrolRolsForUsuIdmodificacion;
        this.tblusuarioUsusForUsuIdcreacion = tblusuarioUsusForUsuIdcreacion;
        this.tblusuarioUsusForUsuIdmodificacion = tblusuarioUsusForUsuIdmodificacion;
    }

    @Id

    @Column(name = "usu_id", unique = true, nullable = false)
    public long getUsuId() {
        return this.usuId;
    }

    public void setUsuId(long usuId) {
        this.usuId = usuId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rol_id", nullable = false)
    public TblrolRol getTblrolRol() {
        return this.tblrolRol;
    }

    public void setTblrolRol(TblrolRol tblrolRol) {
        this.tblrolRol = tblrolRol;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_idcreacion", nullable = false)
    public TblusuarioUsu getTblusuarioUsuByUsuIdcreacion() {
        return this.tblusuarioUsuByUsuIdcreacion;
    }

    public void setTblusuarioUsuByUsuIdcreacion(TblusuarioUsu tblusuarioUsuByUsuIdcreacion) {
        this.tblusuarioUsuByUsuIdcreacion = tblusuarioUsuByUsuIdcreacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usu_idmodificacion")
    public TblusuarioUsu getTblusuarioUsuByUsuIdmodificacion() {
        return this.tblusuarioUsuByUsuIdmodificacion;
    }

    public void setTblusuarioUsuByUsuIdmodificacion(TblusuarioUsu tblusuarioUsuByUsuIdmodificacion) {
        this.tblusuarioUsuByUsuIdmodificacion = tblusuarioUsuByUsuIdmodificacion;
    }

    @Column(name = "usu_nombre", unique = true, length = 12)
    public String getUsuNombre() {
        return this.usuNombre;
    }

    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }

    @Column(name = "usu_contrasenhia", nullable = false, length = 12)
    public String getUsuContrasenhia() {
        return this.usuContrasenhia;
    }

    public void setUsuContrasenhia(String usuContrasenhia) {
        this.usuContrasenhia = usuContrasenhia;
    }

    @Column(name = "usu_nombrecompleto", nullable = false)
    public String getUsuNombrecompleto() {
        return this.usuNombrecompleto;
    }

    public void setUsuNombrecompleto(String usuNombrecompleto) {
        this.usuNombrecompleto = usuNombrecompleto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "usu_fechacreacion", nullable = false, length = 29)
    public Date getUsuFechacreacion() {
        return this.usuFechacreacion;
    }

    public void setUsuFechacreacion(Date usuFechacreacion) {
        this.usuFechacreacion = usuFechacreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "usu_fechamodificacion", length = 29)
    public Date getUsuFechamodificacion() {
        return this.usuFechamodificacion;
    }

    public void setUsuFechamodificacion(Date usuFechamodificacion) {
        this.usuFechamodificacion = usuFechamodificacion;
    }

    @Column(name = "emp_id", nullable = false)
    public long getEmpId() {
        return this.empId;
    }

    public void setEmpId(long empId) {
        this.empId = empId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tblusuarioUsuByUsuIdcreacion")
    public Set<TblrolRol> getTblrolRolsForUsuIdcreacion() {
        return this.tblrolRolsForUsuIdcreacion;
    }

    public void setTblrolRolsForUsuIdcreacion(Set<TblrolRol> tblrolRolsForUsuIdcreacion) {
        this.tblrolRolsForUsuIdcreacion = tblrolRolsForUsuIdcreacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tblusuarioUsuByUsuIdmodificacion")
    public Set<TblrolRol> getTblrolRolsForUsuIdmodificacion() {
        return this.tblrolRolsForUsuIdmodificacion;
    }

    public void setTblrolRolsForUsuIdmodificacion(Set<TblrolRol> tblrolRolsForUsuIdmodificacion) {
        this.tblrolRolsForUsuIdmodificacion = tblrolRolsForUsuIdmodificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tblusuarioUsuByUsuIdcreacion")
    public Set<TblusuarioUsu> getTblusuarioUsusForUsuIdcreacion() {
        return this.tblusuarioUsusForUsuIdcreacion;
    }

    public void setTblusuarioUsusForUsuIdcreacion(Set<TblusuarioUsu> tblusuarioUsusForUsuIdcreacion) {
        this.tblusuarioUsusForUsuIdcreacion = tblusuarioUsusForUsuIdcreacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tblusuarioUsuByUsuIdmodificacion")
    public Set<TblusuarioUsu> getTblusuarioUsusForUsuIdmodificacion() {
        return this.tblusuarioUsusForUsuIdmodificacion;
    }

    public void setTblusuarioUsusForUsuIdmodificacion(Set<TblusuarioUsu> tblusuarioUsusForUsuIdmodificacion) {
        this.tblusuarioUsusForUsuIdmodificacion = tblusuarioUsusForUsuIdmodificacion;
    }

}
