package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DocumentoVentaDetalle generated by hbm2java
 */
public class DocumentoVentaDetalle  implements java.io.Serializable {


     private long id;
     private Usuario usuarioByIdUsuarioModificacion;
     private Usuario usuarioByIdUsuarioCreacion;
     private Producto producto;
     private Unidad unidad;
     private DocumentoVenta documentoVenta;
     private double precioUnitario;
     private double descuentoUnitario;
     private double fleteUnitario;
     private double bonificacionUnitario;
     private double precioFinal;
     private double cantidad;
     private boolean descuento;
     private boolean gratuito;
     private double totalDescuento;
     private double totalGrabado;
     private double totalIgv;
     private double total;
     private Date fechaCreacion;
     private Date fechaModificacion;

    public DocumentoVentaDetalle() {
    }

	
    public DocumentoVentaDetalle(long id, Usuario usuarioByIdUsuarioCreacion, DocumentoVenta documentoVenta, double precioUnitario, double descuentoUnitario, double fleteUnitario, double bonificacionUnitario, double precioFinal, double cantidad, boolean descuento, boolean gratuito, double totalDescuento, double totalGrabado, double totalIgv, double total, Date fechaCreacion) {
        this.id = id;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.documentoVenta = documentoVenta;
        this.precioUnitario = precioUnitario;
        this.descuentoUnitario = descuentoUnitario;
        this.fleteUnitario = fleteUnitario;
        this.bonificacionUnitario = bonificacionUnitario;
        this.precioFinal = precioFinal;
        this.cantidad = cantidad;
        this.descuento = descuento;
        this.gratuito = gratuito;
        this.totalDescuento = totalDescuento;
        this.totalGrabado = totalGrabado;
        this.totalIgv = totalIgv;
        this.total = total;
        this.fechaCreacion = fechaCreacion;
    }
    public DocumentoVentaDetalle(long id, Usuario usuarioByIdUsuarioModificacion, Usuario usuarioByIdUsuarioCreacion, Producto producto, Unidad unidad, DocumentoVenta documentoVenta, double precioUnitario, double descuentoUnitario, double fleteUnitario, double bonificacionUnitario, double precioFinal, double cantidad, boolean descuento, boolean gratuito, double totalDescuento, double totalGrabado, double totalIgv, double total, Date fechaCreacion, Date fechaModificacion) {
       this.id = id;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.producto = producto;
       this.unidad = unidad;
       this.documentoVenta = documentoVenta;
       this.precioUnitario = precioUnitario;
       this.descuentoUnitario = descuentoUnitario;
       this.fleteUnitario = fleteUnitario;
       this.bonificacionUnitario = bonificacionUnitario;
       this.precioFinal = precioFinal;
       this.cantidad = cantidad;
       this.descuento = descuento;
       this.gratuito = gratuito;
       this.totalDescuento = totalDescuento;
       this.totalGrabado = totalGrabado;
       this.totalIgv = totalIgv;
       this.total = total;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public DocumentoVenta getDocumentoVenta() {
        return this.documentoVenta;
    }
    
    public void setDocumentoVenta(DocumentoVenta documentoVenta) {
        this.documentoVenta = documentoVenta;
    }
    public double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public double getDescuentoUnitario() {
        return this.descuentoUnitario;
    }
    
    public void setDescuentoUnitario(double descuentoUnitario) {
        this.descuentoUnitario = descuentoUnitario;
    }
    public double getFleteUnitario() {
        return this.fleteUnitario;
    }
    
    public void setFleteUnitario(double fleteUnitario) {
        this.fleteUnitario = fleteUnitario;
    }
    public double getBonificacionUnitario() {
        return this.bonificacionUnitario;
    }
    
    public void setBonificacionUnitario(double bonificacionUnitario) {
        this.bonificacionUnitario = bonificacionUnitario;
    }
    public double getPrecioFinal() {
        return this.precioFinal;
    }
    
    public void setPrecioFinal(double precioFinal) {
        this.precioFinal = precioFinal;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public boolean isDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(boolean descuento) {
        this.descuento = descuento;
    }
    public boolean isGratuito() {
        return this.gratuito;
    }
    
    public void setGratuito(boolean gratuito) {
        this.gratuito = gratuito;
    }
    public double getTotalDescuento() {
        return this.totalDescuento;
    }
    
    public void setTotalDescuento(double totalDescuento) {
        this.totalDescuento = totalDescuento;
    }
    public double getTotalGrabado() {
        return this.totalGrabado;
    }
    
    public void setTotalGrabado(double totalGrabado) {
        this.totalGrabado = totalGrabado;
    }
    public double getTotalIgv() {
        return this.totalIgv;
    }
    
    public void setTotalIgv(double totalIgv) {
        this.totalIgv = totalIgv;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


