package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocumentoVenta generated by hbm2java
 */
public class DocumentoVenta  implements java.io.Serializable {


     private long id;
     private Usuario usuarioByIdUsuarioModificacion;
     private Usuario usuarioByIdUsuarioCreacion;
     private Empresa empresa;
     private Moneda moneda;
     private EstadoDocumentoVenta estadoDocumentoVenta;
     private PuntoVenta puntoVenta;
     private PuntoVentaSerie puntoVentaSerie;
     private TipoDocumentoVenta tipoDocumentoVenta;
     private String condicion;
     private String formaPago;
     private String banco;
     private String numeroPago;
     private Date fechaEmision;
     private Date fechaVencimiento;
     private String guiaRemision;
     private String numero;
     private Long idCliente;
     private double totalGratuito;
     private double totalDescuento;
     private double totalGrabado;
     private double totalIgv;
     private double total;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set resumenVentasGrupoVentas = new HashSet(0);
     private Set documentoVentaDetalles = new HashSet(0);

    public DocumentoVenta() {
    }

	
    public DocumentoVenta(long id, Usuario usuarioByIdUsuarioCreacion, Empresa empresa, Moneda moneda, EstadoDocumentoVenta estadoDocumentoVenta, PuntoVenta puntoVenta, PuntoVentaSerie puntoVentaSerie, TipoDocumentoVenta tipoDocumentoVenta, String condicion, String formaPago, Date fechaEmision, String numero, double totalGratuito, double totalDescuento, double totalGrabado, double totalIgv, double total, Date fechaCreacion) {
        this.id = id;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.empresa = empresa;
        this.moneda = moneda;
        this.estadoDocumentoVenta = estadoDocumentoVenta;
        this.puntoVenta = puntoVenta;
        this.puntoVentaSerie = puntoVentaSerie;
        this.tipoDocumentoVenta = tipoDocumentoVenta;
        this.condicion = condicion;
        this.formaPago = formaPago;
        this.fechaEmision = fechaEmision;
        this.numero = numero;
        this.totalGratuito = totalGratuito;
        this.totalDescuento = totalDescuento;
        this.totalGrabado = totalGrabado;
        this.totalIgv = totalIgv;
        this.total = total;
        this.fechaCreacion = fechaCreacion;
    }
    public DocumentoVenta(long id, Usuario usuarioByIdUsuarioModificacion, Usuario usuarioByIdUsuarioCreacion, Empresa empresa, Moneda moneda, EstadoDocumentoVenta estadoDocumentoVenta, PuntoVenta puntoVenta, PuntoVentaSerie puntoVentaSerie, TipoDocumentoVenta tipoDocumentoVenta, String condicion, String formaPago, String banco, String numeroPago, Date fechaEmision, Date fechaVencimiento, String guiaRemision, String numero, Long idCliente, double totalGratuito, double totalDescuento, double totalGrabado, double totalIgv, double total, Date fechaCreacion, Date fechaModificacion, Set resumenVentasGrupoVentas, Set documentoVentaDetalles) {
       this.id = id;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.empresa = empresa;
       this.moneda = moneda;
       this.estadoDocumentoVenta = estadoDocumentoVenta;
       this.puntoVenta = puntoVenta;
       this.puntoVentaSerie = puntoVentaSerie;
       this.tipoDocumentoVenta = tipoDocumentoVenta;
       this.condicion = condicion;
       this.formaPago = formaPago;
       this.banco = banco;
       this.numeroPago = numeroPago;
       this.fechaEmision = fechaEmision;
       this.fechaVencimiento = fechaVencimiento;
       this.guiaRemision = guiaRemision;
       this.numero = numero;
       this.idCliente = idCliente;
       this.totalGratuito = totalGratuito;
       this.totalDescuento = totalDescuento;
       this.totalGrabado = totalGrabado;
       this.totalIgv = totalIgv;
       this.total = total;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.resumenVentasGrupoVentas = resumenVentasGrupoVentas;
       this.documentoVentaDetalles = documentoVentaDetalles;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Moneda getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }
    public EstadoDocumentoVenta getEstadoDocumentoVenta() {
        return this.estadoDocumentoVenta;
    }
    
    public void setEstadoDocumentoVenta(EstadoDocumentoVenta estadoDocumentoVenta) {
        this.estadoDocumentoVenta = estadoDocumentoVenta;
    }
    public PuntoVenta getPuntoVenta() {
        return this.puntoVenta;
    }
    
    public void setPuntoVenta(PuntoVenta puntoVenta) {
        this.puntoVenta = puntoVenta;
    }
    public PuntoVentaSerie getPuntoVentaSerie() {
        return this.puntoVentaSerie;
    }
    
    public void setPuntoVentaSerie(PuntoVentaSerie puntoVentaSerie) {
        this.puntoVentaSerie = puntoVentaSerie;
    }
    public TipoDocumentoVenta getTipoDocumentoVenta() {
        return this.tipoDocumentoVenta;
    }
    
    public void setTipoDocumentoVenta(TipoDocumentoVenta tipoDocumentoVenta) {
        this.tipoDocumentoVenta = tipoDocumentoVenta;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }
    public String getNumeroPago() {
        return this.numeroPago;
    }
    
    public void setNumeroPago(String numeroPago) {
        this.numeroPago = numeroPago;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public String getGuiaRemision() {
        return this.guiaRemision;
    }
    
    public void setGuiaRemision(String guiaRemision) {
        this.guiaRemision = guiaRemision;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Long getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Long idCliente) {
        this.idCliente = idCliente;
    }
    public double getTotalGratuito() {
        return this.totalGratuito;
    }
    
    public void setTotalGratuito(double totalGratuito) {
        this.totalGratuito = totalGratuito;
    }
    public double getTotalDescuento() {
        return this.totalDescuento;
    }
    
    public void setTotalDescuento(double totalDescuento) {
        this.totalDescuento = totalDescuento;
    }
    public double getTotalGrabado() {
        return this.totalGrabado;
    }
    
    public void setTotalGrabado(double totalGrabado) {
        this.totalGrabado = totalGrabado;
    }
    public double getTotalIgv() {
        return this.totalIgv;
    }
    
    public void setTotalIgv(double totalIgv) {
        this.totalIgv = totalIgv;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getResumenVentasGrupoVentas() {
        return this.resumenVentasGrupoVentas;
    }
    
    public void setResumenVentasGrupoVentas(Set resumenVentasGrupoVentas) {
        this.resumenVentasGrupoVentas = resumenVentasGrupoVentas;
    }
    public Set getDocumentoVentaDetalles() {
        return this.documentoVentaDetalles;
    }
    
    public void setDocumentoVentaDetalles(Set documentoVentaDetalles) {
        this.documentoVentaDetalles = documentoVentaDetalles;
    }




}


