package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private long id;
     private Usuario usuarioByIdUsuarioModificacion;
     private Usuario usuarioByIdUsuarioCreacion;
     private Entidad entidad;
     private String correoAdmin;
     private String contrasenhiaCorreo;
     private String logo;
     private boolean activo;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set resumenVentases = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set productos = new HashSet(0);
     private Set puntoVentas = new HashSet(0);
     private Set documentoVentas = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(long id, Usuario usuarioByIdUsuarioCreacion, Entidad entidad, boolean activo, Date fechaCreacion) {
        this.id = id;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.entidad = entidad;
        this.activo = activo;
        this.fechaCreacion = fechaCreacion;
    }
    public Empresa(long id, Usuario usuarioByIdUsuarioModificacion, Usuario usuarioByIdUsuarioCreacion, Entidad entidad, String correoAdmin, String contrasenhiaCorreo, String logo, boolean activo, Date fechaCreacion, Date fechaModificacion, Set resumenVentases, Set usuarios, Set productos, Set puntoVentas, Set documentoVentas) {
       this.id = id;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.entidad = entidad;
       this.correoAdmin = correoAdmin;
       this.contrasenhiaCorreo = contrasenhiaCorreo;
       this.logo = logo;
       this.activo = activo;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.resumenVentases = resumenVentases;
       this.usuarios = usuarios;
       this.productos = productos;
       this.puntoVentas = puntoVentas;
       this.documentoVentas = documentoVentas;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public Entidad getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }
    public String getCorreoAdmin() {
        return this.correoAdmin;
    }
    
    public void setCorreoAdmin(String correoAdmin) {
        this.correoAdmin = correoAdmin;
    }
    public String getContrasenhiaCorreo() {
        return this.contrasenhiaCorreo;
    }
    
    public void setContrasenhiaCorreo(String contrasenhiaCorreo) {
        this.contrasenhiaCorreo = contrasenhiaCorreo;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getResumenVentases() {
        return this.resumenVentases;
    }
    
    public void setResumenVentases(Set resumenVentases) {
        this.resumenVentases = resumenVentases;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }
    public Set getPuntoVentas() {
        return this.puntoVentas;
    }
    
    public void setPuntoVentas(Set puntoVentas) {
        this.puntoVentas = puntoVentas;
    }
    public Set getDocumentoVentas() {
        return this.documentoVentas;
    }
    
    public void setDocumentoVentas(Set documentoVentas) {
        this.documentoVentas = documentoVentas;
    }




}


