package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Entidad generated by hbm2java
 */
public class Entidad  implements java.io.Serializable {


     private long id;
     private Usuario usuarioByIdUsuarioModificacion;
     private Usuario usuarioByIdUsuarioCreacion;
     private TipoDocumentoEntidad tipoDocumentoEntidad;
     private Ubigeo ubigeo;
     private String documento;
     private String nombre;
     private String codigoPais;
     private String zona;
     private String direccion;
     private String correoElectronico1;
     private String correoElectronico2;
     private String correoElectronico3;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set usuarios = new HashSet(0);
     private Set empresas = new HashSet(0);

    public Entidad() {
    }

	
    public Entidad(long id, Usuario usuarioByIdUsuarioCreacion, TipoDocumentoEntidad tipoDocumentoEntidad, String documento, String nombre, Date fechaCreacion) {
        this.id = id;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.tipoDocumentoEntidad = tipoDocumentoEntidad;
        this.documento = documento;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
    }
    public Entidad(long id, Usuario usuarioByIdUsuarioModificacion, Usuario usuarioByIdUsuarioCreacion, TipoDocumentoEntidad tipoDocumentoEntidad, Ubigeo ubigeo, String documento, String nombre, String codigoPais, String zona, String direccion, String correoElectronico1, String correoElectronico2, String correoElectronico3, Date fechaCreacion, Date fechaModificacion, Set usuarios, Set empresas) {
       this.id = id;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.tipoDocumentoEntidad = tipoDocumentoEntidad;
       this.ubigeo = ubigeo;
       this.documento = documento;
       this.nombre = nombre;
       this.codigoPais = codigoPais;
       this.zona = zona;
       this.direccion = direccion;
       this.correoElectronico1 = correoElectronico1;
       this.correoElectronico2 = correoElectronico2;
       this.correoElectronico3 = correoElectronico3;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuarios = usuarios;
       this.empresas = empresas;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public TipoDocumentoEntidad getTipoDocumentoEntidad() {
        return this.tipoDocumentoEntidad;
    }
    
    public void setTipoDocumentoEntidad(TipoDocumentoEntidad tipoDocumentoEntidad) {
        this.tipoDocumentoEntidad = tipoDocumentoEntidad;
    }
    public Ubigeo getUbigeo() {
        return this.ubigeo;
    }
    
    public void setUbigeo(Ubigeo ubigeo) {
        this.ubigeo = ubigeo;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigoPais() {
        return this.codigoPais;
    }
    
    public void setCodigoPais(String codigoPais) {
        this.codigoPais = codigoPais;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreoElectronico1() {
        return this.correoElectronico1;
    }
    
    public void setCorreoElectronico1(String correoElectronico1) {
        this.correoElectronico1 = correoElectronico1;
    }
    public String getCorreoElectronico2() {
        return this.correoElectronico2;
    }
    
    public void setCorreoElectronico2(String correoElectronico2) {
        this.correoElectronico2 = correoElectronico2;
    }
    public String getCorreoElectronico3() {
        return this.correoElectronico3;
    }
    
    public void setCorreoElectronico3(String correoElectronico3) {
        this.correoElectronico3 = correoElectronico3;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


