package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Operacion generated by hbm2java
 */
public class Operacion  implements java.io.Serializable {


     private long id;
     private Menu menu;
     private Usuario usuarioByIdUsuarioCreacion;
     private Usuario usuarioByIdUsuarioModificacion;
     private String nombre;
     private boolean activo;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set rolMenuOperacions = new HashSet(0);

    public Operacion() {
    }

	
    public Operacion(long id, Menu menu, Usuario usuarioByIdUsuarioCreacion, String nombre, boolean activo, Date fechaCreacion) {
        this.id = id;
        this.menu = menu;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.nombre = nombre;
        this.activo = activo;
        this.fechaCreacion = fechaCreacion;
    }
    public Operacion(long id, Menu menu, Usuario usuarioByIdUsuarioCreacion, Usuario usuarioByIdUsuarioModificacion, String nombre, boolean activo, Date fechaCreacion, Date fechaModificacion, Set rolMenuOperacions) {
       this.id = id;
       this.menu = menu;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.nombre = nombre;
       this.activo = activo;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.rolMenuOperacions = rolMenuOperacions;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getRolMenuOperacions() {
        return this.rolMenuOperacions;
    }
    
    public void setRolMenuOperacions(Set rolMenuOperacions) {
        this.rolMenuOperacions = rolMenuOperacions;
    }




}


