package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PuntoVentaSerie generated by hbm2java
 */
public class PuntoVentaSerie  implements java.io.Serializable {


     private String codigo;
     private Usuario usuarioByIdUsuarioCreacion;
     private Usuario usuarioByIdUsuarioModificacion;
     private PuntoVenta puntoVenta;
     private TipoDocumentoVenta tipoDocumentoVenta;
     private String ultimoCorrelativo;
     private boolean activo;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set resumenVentasGrupos = new HashSet(0);
     private Set documentoVentas = new HashSet(0);

    public PuntoVentaSerie() {
    }

	
    public PuntoVentaSerie(String codigo, Usuario usuarioByIdUsuarioCreacion, PuntoVenta puntoVenta, TipoDocumentoVenta tipoDocumentoVenta, String ultimoCorrelativo, boolean activo, Date fechaCreacion) {
        this.codigo = codigo;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.puntoVenta = puntoVenta;
        this.tipoDocumentoVenta = tipoDocumentoVenta;
        this.ultimoCorrelativo = ultimoCorrelativo;
        this.activo = activo;
        this.fechaCreacion = fechaCreacion;
    }
    public PuntoVentaSerie(String codigo, Usuario usuarioByIdUsuarioCreacion, Usuario usuarioByIdUsuarioModificacion, PuntoVenta puntoVenta, TipoDocumentoVenta tipoDocumentoVenta, String ultimoCorrelativo, boolean activo, Date fechaCreacion, Date fechaModificacion, Set resumenVentasGrupos, Set documentoVentas) {
       this.codigo = codigo;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.puntoVenta = puntoVenta;
       this.tipoDocumentoVenta = tipoDocumentoVenta;
       this.ultimoCorrelativo = ultimoCorrelativo;
       this.activo = activo;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.resumenVentasGrupos = resumenVentasGrupos;
       this.documentoVentas = documentoVentas;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public PuntoVenta getPuntoVenta() {
        return this.puntoVenta;
    }
    
    public void setPuntoVenta(PuntoVenta puntoVenta) {
        this.puntoVenta = puntoVenta;
    }
    public TipoDocumentoVenta getTipoDocumentoVenta() {
        return this.tipoDocumentoVenta;
    }
    
    public void setTipoDocumentoVenta(TipoDocumentoVenta tipoDocumentoVenta) {
        this.tipoDocumentoVenta = tipoDocumentoVenta;
    }
    public String getUltimoCorrelativo() {
        return this.ultimoCorrelativo;
    }
    
    public void setUltimoCorrelativo(String ultimoCorrelativo) {
        this.ultimoCorrelativo = ultimoCorrelativo;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getResumenVentasGrupos() {
        return this.resumenVentasGrupos;
    }
    
    public void setResumenVentasGrupos(Set resumenVentasGrupos) {
        this.resumenVentasGrupos = resumenVentasGrupos;
    }
    public Set getDocumentoVentas() {
        return this.documentoVentas;
    }
    
    public void setDocumentoVentas(Set documentoVentas) {
        this.documentoVentas = documentoVentas;
    }




}


