package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PuntoVenta generated by hbm2java
 */
public class PuntoVenta  implements java.io.Serializable {


     private long id;
     private Usuario usuarioByIdUsuarioModificacion;
     private Usuario usuarioByIdUsuarioCreacion;
     private Empresa empresa;
     private String nombre;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set documentoVentas = new HashSet(0);
     private Set puntoVentaSeries = new HashSet(0);

    public PuntoVenta() {
    }

	
    public PuntoVenta(long id, Usuario usuarioByIdUsuarioCreacion, Empresa empresa, String nombre, Date fechaCreacion) {
        this.id = id;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.empresa = empresa;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
    }
    public PuntoVenta(long id, Usuario usuarioByIdUsuarioModificacion, Usuario usuarioByIdUsuarioCreacion, Empresa empresa, String nombre, Date fechaCreacion, Date fechaModificacion, Set documentoVentas, Set puntoVentaSeries) {
       this.id = id;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.empresa = empresa;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.documentoVentas = documentoVentas;
       this.puntoVentaSeries = puntoVentaSeries;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getDocumentoVentas() {
        return this.documentoVentas;
    }
    
    public void setDocumentoVentas(Set documentoVentas) {
        this.documentoVentas = documentoVentas;
    }
    public Set getPuntoVentaSeries() {
        return this.puntoVentaSeries;
    }
    
    public void setPuntoVentaSeries(Set puntoVentaSeries) {
        this.puntoVentaSeries = puntoVentaSeries;
    }




}


