package pe.modelo.pojo;
// Generated 17-ago-2017 14:14:43 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PuntoVentaSerie generated by hbm2java
 */
@Entity
@Table(name="punto_venta_serie"
    ,schema="ventas"
)
public class PuntoVentaSerie  implements java.io.Serializable {


     private String codigo;
     @JsonIgnore
     private Usuario usuarioByIdUsuarioCreacion;
     @JsonIgnore
     private Usuario usuarioByIdUsuarioModificacion;
     private PuntoVenta puntoVenta;
     private TipoDocumentoVenta tipoDocumentoVenta;
     private String ultimoCorrelativo;
     private boolean activo;
     private Date fechaCreacion;
     private Date fechaModificacion;
     @JsonIgnore
     private Set<ResumenVentasGrupo> resumenVentasGrupos = new HashSet<ResumenVentasGrupo>(0);
     @JsonIgnore
     private Set<DocumentoVenta> documentoVentas = new HashSet<DocumentoVenta>(0);

    public PuntoVentaSerie() {
    }

	
    public PuntoVentaSerie(String codigo, Usuario usuarioByIdUsuarioCreacion, PuntoVenta puntoVenta, TipoDocumentoVenta tipoDocumentoVenta, String ultimoCorrelativo, boolean activo, Date fechaCreacion) {
        this.codigo = codigo;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.puntoVenta = puntoVenta;
        this.tipoDocumentoVenta = tipoDocumentoVenta;
        this.ultimoCorrelativo = ultimoCorrelativo;
        this.activo = activo;
        this.fechaCreacion = fechaCreacion;
    }
    public PuntoVentaSerie(String codigo, Usuario usuarioByIdUsuarioCreacion, Usuario usuarioByIdUsuarioModificacion, PuntoVenta puntoVenta, TipoDocumentoVenta tipoDocumentoVenta, String ultimoCorrelativo, boolean activo, Date fechaCreacion, Date fechaModificacion, Set<ResumenVentasGrupo> resumenVentasGrupos, Set<DocumentoVenta> documentoVentas) {
       this.codigo = codigo;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.puntoVenta = puntoVenta;
       this.tipoDocumentoVenta = tipoDocumentoVenta;
       this.ultimoCorrelativo = ultimoCorrelativo;
       this.activo = activo;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.resumenVentasGrupos = resumenVentasGrupos;
       this.documentoVentas = documentoVentas;
    }
   
     @Id 

    
    @Column(name="codigo", unique=true, nullable=false, length=4)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario_creacion", nullable=false)
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario_modificacion")
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_punto_venta", nullable=false)
    public PuntoVenta getPuntoVenta() {
        return this.puntoVenta;
    }
    
    public void setPuntoVenta(PuntoVenta puntoVenta) {
        this.puntoVenta = puntoVenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_tipo_documento_venta", nullable=false)
    public TipoDocumentoVenta getTipoDocumentoVenta() {
        return this.tipoDocumentoVenta;
    }
    
    public void setTipoDocumentoVenta(TipoDocumentoVenta tipoDocumentoVenta) {
        this.tipoDocumentoVenta = tipoDocumentoVenta;
    }

    
    @Column(name="ultimo_correlativo", nullable=false, length=8)
    public String getUltimoCorrelativo() {
        return this.ultimoCorrelativo;
    }
    
    public void setUltimoCorrelativo(String ultimoCorrelativo) {
        this.ultimoCorrelativo = ultimoCorrelativo;
    }

    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", nullable=false, length=29)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=29)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="puntoVentaSerie")
    public Set<ResumenVentasGrupo> getResumenVentasGrupos() {
        return this.resumenVentasGrupos;
    }
    
    public void setResumenVentasGrupos(Set<ResumenVentasGrupo> resumenVentasGrupos) {
        this.resumenVentasGrupos = resumenVentasGrupos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="puntoVentaSerie")
    public Set<DocumentoVenta> getDocumentoVentas() {
        return this.documentoVentas;
    }
    
    public void setDocumentoVentas(Set<DocumentoVenta> documentoVentas) {
        this.documentoVentas = documentoVentas;
    }




}


