package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ResumenVentas generated by hbm2java
 */
public class ResumenVentas  implements java.io.Serializable {


     private long id;
     private Usuario usuarioByIdUsuarioModificacion;
     private Usuario usuarioByIdUsuarioCreacion;
     private Empresa empresa;
     private EstadoDocumentoVenta estadoDocumentoVenta;
     private String tipo;
     private Date fechaEmision;
     private String numero;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set resumenVentasGrupos = new HashSet(0);

    public ResumenVentas() {
    }

	
    public ResumenVentas(long id, Usuario usuarioByIdUsuarioCreacion, Empresa empresa, EstadoDocumentoVenta estadoDocumentoVenta, String tipo, Date fechaEmision, String numero, Date fechaCreacion) {
        this.id = id;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.empresa = empresa;
        this.estadoDocumentoVenta = estadoDocumentoVenta;
        this.tipo = tipo;
        this.fechaEmision = fechaEmision;
        this.numero = numero;
        this.fechaCreacion = fechaCreacion;
    }
    public ResumenVentas(long id, Usuario usuarioByIdUsuarioModificacion, Usuario usuarioByIdUsuarioCreacion, Empresa empresa, EstadoDocumentoVenta estadoDocumentoVenta, String tipo, Date fechaEmision, String numero, Date fechaCreacion, Date fechaModificacion, Set resumenVentasGrupos) {
       this.id = id;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.empresa = empresa;
       this.estadoDocumentoVenta = estadoDocumentoVenta;
       this.tipo = tipo;
       this.fechaEmision = fechaEmision;
       this.numero = numero;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.resumenVentasGrupos = resumenVentasGrupos;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public EstadoDocumentoVenta getEstadoDocumentoVenta() {
        return this.estadoDocumentoVenta;
    }
    
    public void setEstadoDocumentoVenta(EstadoDocumentoVenta estadoDocumentoVenta) {
        this.estadoDocumentoVenta = estadoDocumentoVenta;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getResumenVentasGrupos() {
        return this.resumenVentasGrupos;
    }
    
    public void setResumenVentasGrupos(Set resumenVentasGrupos) {
        this.resumenVentasGrupos = resumenVentasGrupos;
    }




}


