package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ResumenVentasGrupoVenta generated by hbm2java
 */
public class ResumenVentasGrupoVenta  implements java.io.Serializable {


     private long id;
     private Usuario usuarioByIdUsuarioCreacion;
     private Usuario usuarioByIdUsuarioModificacion;
     private DocumentoVenta documentoVenta;
     private ResumenVentasGrupo resumenVentasGrupo;
     private Date fechaCreacion;
     private Date fechaModificacion;

    public ResumenVentasGrupoVenta() {
    }

	
    public ResumenVentasGrupoVenta(long id, Usuario usuarioByIdUsuarioCreacion, DocumentoVenta documentoVenta, ResumenVentasGrupo resumenVentasGrupo, Date fechaCreacion) {
        this.id = id;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.documentoVenta = documentoVenta;
        this.resumenVentasGrupo = resumenVentasGrupo;
        this.fechaCreacion = fechaCreacion;
    }
    public ResumenVentasGrupoVenta(long id, Usuario usuarioByIdUsuarioCreacion, Usuario usuarioByIdUsuarioModificacion, DocumentoVenta documentoVenta, ResumenVentasGrupo resumenVentasGrupo, Date fechaCreacion, Date fechaModificacion) {
       this.id = id;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.documentoVenta = documentoVenta;
       this.resumenVentasGrupo = resumenVentasGrupo;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public DocumentoVenta getDocumentoVenta() {
        return this.documentoVenta;
    }
    
    public void setDocumentoVenta(DocumentoVenta documentoVenta) {
        this.documentoVenta = documentoVenta;
    }
    public ResumenVentasGrupo getResumenVentasGrupo() {
        return this.resumenVentasGrupo;
    }
    
    public void setResumenVentasGrupo(ResumenVentasGrupo resumenVentasGrupo) {
        this.resumenVentasGrupo = resumenVentasGrupo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


