package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ResumenVentasGrupo generated by hbm2java
 */
public class ResumenVentasGrupo  implements java.io.Serializable {


     private long id;
     private Usuario usuarioByIdUsuarioModificacion;
     private Usuario usuarioByIdUsuarioCreacion;
     private Moneda moneda;
     private PuntoVentaSerie puntoVentaSerie;
     private ResumenVentas resumenVentas;
     private TipoDocumentoVenta tipoDocumentoVenta;
     private String inicioDocumentoVenta;
     private String finDocumentoVenta;
     private String descripcion;
     private Double totalGrabado;
     private Double totalIgv;
     private Double total;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set resumenVentasGrupoVentas = new HashSet(0);

    public ResumenVentasGrupo() {
    }

	
    public ResumenVentasGrupo(long id, Usuario usuarioByIdUsuarioCreacion, PuntoVentaSerie puntoVentaSerie, ResumenVentas resumenVentas, TipoDocumentoVenta tipoDocumentoVenta, String inicioDocumentoVenta, String finDocumentoVenta, Date fechaCreacion) {
        this.id = id;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.puntoVentaSerie = puntoVentaSerie;
        this.resumenVentas = resumenVentas;
        this.tipoDocumentoVenta = tipoDocumentoVenta;
        this.inicioDocumentoVenta = inicioDocumentoVenta;
        this.finDocumentoVenta = finDocumentoVenta;
        this.fechaCreacion = fechaCreacion;
    }
    public ResumenVentasGrupo(long id, Usuario usuarioByIdUsuarioModificacion, Usuario usuarioByIdUsuarioCreacion, Moneda moneda, PuntoVentaSerie puntoVentaSerie, ResumenVentas resumenVentas, TipoDocumentoVenta tipoDocumentoVenta, String inicioDocumentoVenta, String finDocumentoVenta, String descripcion, Double totalGrabado, Double totalIgv, Double total, Date fechaCreacion, Date fechaModificacion, Set resumenVentasGrupoVentas) {
       this.id = id;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.moneda = moneda;
       this.puntoVentaSerie = puntoVentaSerie;
       this.resumenVentas = resumenVentas;
       this.tipoDocumentoVenta = tipoDocumentoVenta;
       this.inicioDocumentoVenta = inicioDocumentoVenta;
       this.finDocumentoVenta = finDocumentoVenta;
       this.descripcion = descripcion;
       this.totalGrabado = totalGrabado;
       this.totalIgv = totalIgv;
       this.total = total;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.resumenVentasGrupoVentas = resumenVentasGrupoVentas;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public Moneda getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }
    public PuntoVentaSerie getPuntoVentaSerie() {
        return this.puntoVentaSerie;
    }
    
    public void setPuntoVentaSerie(PuntoVentaSerie puntoVentaSerie) {
        this.puntoVentaSerie = puntoVentaSerie;
    }
    public ResumenVentas getResumenVentas() {
        return this.resumenVentas;
    }
    
    public void setResumenVentas(ResumenVentas resumenVentas) {
        this.resumenVentas = resumenVentas;
    }
    public TipoDocumentoVenta getTipoDocumentoVenta() {
        return this.tipoDocumentoVenta;
    }
    
    public void setTipoDocumentoVenta(TipoDocumentoVenta tipoDocumentoVenta) {
        this.tipoDocumentoVenta = tipoDocumentoVenta;
    }
    public String getInicioDocumentoVenta() {
        return this.inicioDocumentoVenta;
    }
    
    public void setInicioDocumentoVenta(String inicioDocumentoVenta) {
        this.inicioDocumentoVenta = inicioDocumentoVenta;
    }
    public String getFinDocumentoVenta() {
        return this.finDocumentoVenta;
    }
    
    public void setFinDocumentoVenta(String finDocumentoVenta) {
        this.finDocumentoVenta = finDocumentoVenta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getTotalGrabado() {
        return this.totalGrabado;
    }
    
    public void setTotalGrabado(Double totalGrabado) {
        this.totalGrabado = totalGrabado;
    }
    public Double getTotalIgv() {
        return this.totalIgv;
    }
    
    public void setTotalIgv(Double totalIgv) {
        this.totalIgv = totalIgv;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getResumenVentasGrupoVentas() {
        return this.resumenVentasGrupoVentas;
    }
    
    public void setResumenVentasGrupoVentas(Set resumenVentasGrupoVentas) {
        this.resumenVentasGrupoVentas = resumenVentasGrupoVentas;
    }




}


