package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RolMenu generated by hbm2java
 */
public class RolMenu  implements java.io.Serializable {


     private long id;
     private Menu menu;
     private Rol rol;
     private Usuario usuarioByIdUsuarioModificacion;
     private Usuario usuarioByIdUsuarioCreacion;
     private Date fechaCreacion;
     private Date fechaModificacion;

    public RolMenu() {
    }

	
    public RolMenu(long id, Menu menu, Rol rol, Usuario usuarioByIdUsuarioCreacion, Date fechaCreacion) {
        this.id = id;
        this.menu = menu;
        this.rol = rol;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.fechaCreacion = fechaCreacion;
    }
    public RolMenu(long id, Menu menu, Rol rol, Usuario usuarioByIdUsuarioModificacion, Usuario usuarioByIdUsuarioCreacion, Date fechaCreacion, Date fechaModificacion) {
       this.id = id;
       this.menu = menu;
       this.rol = rol;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


