package pe.modelo.pojo;
// Generated 14-ago-2017 12:43:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RolMenuOperacion generated by hbm2java
 */
public class RolMenuOperacion  implements java.io.Serializable {


     private long id;
     private Operacion operacion;
     private Usuario usuarioByIdUsuarioCreacion;
     private Usuario usuarioByIdUsuarioModificacion;
     private Date fechaCreacion;
     private Date fechaModificacion;

    public RolMenuOperacion() {
    }

	
    public RolMenuOperacion(long id, Operacion operacion, Usuario usuarioByIdUsuarioCreacion, Date fechaCreacion) {
        this.id = id;
        this.operacion = operacion;
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
        this.fechaCreacion = fechaCreacion;
    }
    public RolMenuOperacion(long id, Operacion operacion, Usuario usuarioByIdUsuarioCreacion, Usuario usuarioByIdUsuarioModificacion, Date fechaCreacion, Date fechaModificacion) {
       this.id = id;
       this.operacion = operacion;
       this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
       this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Operacion getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(Operacion operacion) {
        this.operacion = operacion;
    }
    public Usuario getUsuarioByIdUsuarioCreacion() {
        return this.usuarioByIdUsuarioCreacion;
    }
    
    public void setUsuarioByIdUsuarioCreacion(Usuario usuarioByIdUsuarioCreacion) {
        this.usuarioByIdUsuarioCreacion = usuarioByIdUsuarioCreacion;
    }
    public Usuario getUsuarioByIdUsuarioModificacion() {
        return this.usuarioByIdUsuarioModificacion;
    }
    
    public void setUsuarioByIdUsuarioModificacion(Usuario usuarioByIdUsuarioModificacion) {
        this.usuarioByIdUsuarioModificacion = usuarioByIdUsuarioModificacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


