package pe.modelo.pojo;
// Generated 29-ago-2017 18:25:42 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwSelDocumentoVentaId generated by hbm2java
 */
@Embeddable
public class VwSelDocumentoVentaId  implements java.io.Serializable {


     private Long id;
     private String codigoTipoDocumentoVenta;
     private String codigoEstadoDocumentoVenta;
     private String serie;
     private String numero;
     private Date fechaEmision;
     private Long idCliente;
     private Double total;

    public VwSelDocumentoVentaId() {
    }

    public VwSelDocumentoVentaId(Long id, String codigoTipoDocumentoVenta, String codigoEstadoDocumentoVenta, String serie, String numero, Date fechaEmision, Long idCliente, Double total) {
       this.id = id;
       this.codigoTipoDocumentoVenta = codigoTipoDocumentoVenta;
       this.codigoEstadoDocumentoVenta = codigoEstadoDocumentoVenta;
       this.serie = serie;
       this.numero = numero;
       this.fechaEmision = fechaEmision;
       this.idCliente = idCliente;
       this.total = total;
    }
   


    @Column(name="id")
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }


    @Column(name="codigo_tipo_documento_venta", length=2)
    public String getCodigoTipoDocumentoVenta() {
        return this.codigoTipoDocumentoVenta;
    }
    
    public void setCodigoTipoDocumentoVenta(String codigoTipoDocumentoVenta) {
        this.codigoTipoDocumentoVenta = codigoTipoDocumentoVenta;
    }


    @Column(name="codigo_estado_documento_venta", length=3)
    public String getCodigoEstadoDocumentoVenta() {
        return this.codigoEstadoDocumentoVenta;
    }
    
    public void setCodigoEstadoDocumentoVenta(String codigoEstadoDocumentoVenta) {
        this.codigoEstadoDocumentoVenta = codigoEstadoDocumentoVenta;
    }


    @Column(name="serie", length=4)
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }


    @Column(name="numero", length=8)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }


    @Column(name="fecha_emision", length=13)
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }


    @Column(name="id_cliente")
    public Long getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Long idCliente) {
        this.idCliente = idCliente;
    }


    @Column(name="total", precision=17, scale=17)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VwSelDocumentoVentaId) ) return false;
		 VwSelDocumentoVentaId castOther = ( VwSelDocumentoVentaId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getCodigoTipoDocumentoVenta()==castOther.getCodigoTipoDocumentoVenta()) || ( this.getCodigoTipoDocumentoVenta()!=null && castOther.getCodigoTipoDocumentoVenta()!=null && this.getCodigoTipoDocumentoVenta().equals(castOther.getCodigoTipoDocumentoVenta()) ) )
 && ( (this.getCodigoEstadoDocumentoVenta()==castOther.getCodigoEstadoDocumentoVenta()) || ( this.getCodigoEstadoDocumentoVenta()!=null && castOther.getCodigoEstadoDocumentoVenta()!=null && this.getCodigoEstadoDocumentoVenta().equals(castOther.getCodigoEstadoDocumentoVenta()) ) )
 && ( (this.getSerie()==castOther.getSerie()) || ( this.getSerie()!=null && castOther.getSerie()!=null && this.getSerie().equals(castOther.getSerie()) ) )
 && ( (this.getNumero()==castOther.getNumero()) || ( this.getNumero()!=null && castOther.getNumero()!=null && this.getNumero().equals(castOther.getNumero()) ) )
 && ( (this.getFechaEmision()==castOther.getFechaEmision()) || ( this.getFechaEmision()!=null && castOther.getFechaEmision()!=null && this.getFechaEmision().equals(castOther.getFechaEmision()) ) )
 && ( (this.getIdCliente()==castOther.getIdCliente()) || ( this.getIdCliente()!=null && castOther.getIdCliente()!=null && this.getIdCliente().equals(castOther.getIdCliente()) ) )
 && ( (this.getTotal()==castOther.getTotal()) || ( this.getTotal()!=null && castOther.getTotal()!=null && this.getTotal().equals(castOther.getTotal()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getCodigoTipoDocumentoVenta() == null ? 0 : this.getCodigoTipoDocumentoVenta().hashCode() );
         result = 37 * result + ( getCodigoEstadoDocumentoVenta() == null ? 0 : this.getCodigoEstadoDocumentoVenta().hashCode() );
         result = 37 * result + ( getSerie() == null ? 0 : this.getSerie().hashCode() );
         result = 37 * result + ( getNumero() == null ? 0 : this.getNumero().hashCode() );
         result = 37 * result + ( getFechaEmision() == null ? 0 : this.getFechaEmision().hashCode() );
         result = 37 * result + ( getIdCliente() == null ? 0 : this.getIdCliente().hashCode() );
         result = 37 * result + ( getTotal() == null ? 0 : this.getTotal().hashCode() );
         return result;
   }   


}


