package pe.modelo.pojo;
// Generated 29-ago-2017 18:25:42 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwSelDocumentoVenta generated by hbm2java
 */
@Entity
@Table(name="vw_sel_documento_venta"
    ,schema="ventas"
)
public class VwSelDocumentoVenta  implements java.io.Serializable {


     private VwSelDocumentoVentaId id;

    public VwSelDocumentoVenta() {
    }

    public VwSelDocumentoVenta(VwSelDocumentoVentaId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id") ), 
        @AttributeOverride(name="codigoTipoDocumentoVenta", column=@Column(name="codigo_tipo_documento_venta", length=2) ), 
        @AttributeOverride(name="codigoEstadoDocumentoVenta", column=@Column(name="codigo_estado_documento_venta", length=3) ), 
        @AttributeOverride(name="serie", column=@Column(name="serie", length=4) ), 
        @AttributeOverride(name="numero", column=@Column(name="numero", length=8) ), 
        @AttributeOverride(name="fechaEmision", column=@Column(name="fecha_emision", length=13) ), 
        @AttributeOverride(name="idCliente", column=@Column(name="id_cliente") ), 
        @AttributeOverride(name="total", column=@Column(name="total", precision=17, scale=17) ) } )
    public VwSelDocumentoVentaId getId() {
        return this.id;
    }
    
    public void setId(VwSelDocumentoVentaId id) {
        this.id = id;
    }




}


