package pe.modelo.pojo;
// Generated 29-ago-2017 18:25:42 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VwSelDocumentoVenta generated by hbm2java
 */
@Entity
@Table(name = "vw_sel_documento_venta",
        schema = "ventas"
)
public class VwSelDocumentoVenta implements java.io.Serializable {

    private Long id;
    private String codigoTipo;
    private String nombreTipo;
    private String codigoEstado;
    private String nombreEstado;
    private String serie;
    private String numero;
    private Date fechaEmision;
    private String documentoCliente;
    private String nombreCliente;
    private Double total;

    public VwSelDocumentoVenta() {
    }

    @Id
    @Column(name = "id", insertable = false, updatable = false)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "codigo_tipo", length = 2, insertable = false, updatable = false)
    public String getCodigoTipo() {
        return codigoTipo;
    }

    public void setCodigoTipo(String codigoTipo) {
        this.codigoTipo = codigoTipo;
    }

    @Column(name = "nombre_tipo", insertable = false, updatable = false)
    public String getNombreTipo() {
        return nombreTipo;
    }

    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }

    @Column(name = "codigo_estado", length = 3, insertable = false, updatable = false)
    public String getCodigoEstado() {
        return codigoEstado;
    }

    public void setCodigoEstado(String codigoEstado) {
        this.codigoEstado = codigoEstado;
    }

    @Column(name = "nombre_estado", insertable = false, updatable = false)
    public String getNombreEstado() {
        return nombreEstado;
    }

    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }

    @Column(name = "serie", length = 4, insertable = false, updatable = false)
    public String getSerie() {
        return serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    @Column(name = "numero", length = 8, insertable = false, updatable = false)
    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @Column(name = "fecha_emision", length = 13, insertable = false, updatable = false)
    public Date getFechaEmision() {
        return fechaEmision;
    }

    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    @Column(name = "documento_cliente", length = 11, insertable = false, updatable = false)
    public String getDocumentoCliente() {
        return documentoCliente;
    }

    public void setDocumentoCliente(String documentoCliente) {
        this.documentoCliente = documentoCliente;
    }

    @Column(name = "nombre_cliente", insertable = false, updatable = false)
    public String getNombreCliente() {
        return nombreCliente;
    }

    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }

    @Column(name = "total", precision = 17, scale = 17, insertable = false, updatable = false)
    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }
}
